// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostChatroomsChatroomHashMessagesHandlerFunc turns a function with the right signature into a post chatrooms chatroom hash messages handler
type PostChatroomsChatroomHashMessagesHandlerFunc func(PostChatroomsChatroomHashMessagesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostChatroomsChatroomHashMessagesHandlerFunc) Handle(params PostChatroomsChatroomHashMessagesParams) middleware.Responder {
	return fn(params)
}

// PostChatroomsChatroomHashMessagesHandler interface for that can handle valid post chatrooms chatroom hash messages params
type PostChatroomsChatroomHashMessagesHandler interface {
	Handle(PostChatroomsChatroomHashMessagesParams) middleware.Responder
}

// NewPostChatroomsChatroomHashMessages creates a new http.Handler for the post chatrooms chatroom hash messages operation
func NewPostChatroomsChatroomHashMessages(ctx *middleware.Context, handler PostChatroomsChatroomHashMessagesHandler) *PostChatroomsChatroomHashMessages {
	return &PostChatroomsChatroomHashMessages{Context: ctx, Handler: handler}
}

/*PostChatroomsChatroomHashMessages swagger:route POST /chatrooms/{chatroom_hash}/messages messages postChatroomsChatroomHashMessages

メッセージの投稿

*/
type PostChatroomsChatroomHashMessages struct {
	Context *middleware.Context
	Handler PostChatroomsChatroomHashMessagesHandler
}

func (o *PostChatroomsChatroomHashMessages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostChatroomsChatroomHashMessagesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
