// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// NewPostChatroomsChatroomHashMessagesParams creates a new PostChatroomsChatroomHashMessagesParams object
// no default values defined in spec.
func NewPostChatroomsChatroomHashMessagesParams() PostChatroomsChatroomHashMessagesParams {

	return PostChatroomsChatroomHashMessagesParams{}
}

// PostChatroomsChatroomHashMessagesParams contains all the bound params for the post chatrooms chatroom hash messages operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostChatroomsChatroomHashMessages
type PostChatroomsChatroomHashMessagesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Body *apimodel.MessageRequest
	/*長いハッシュ値
	  Required: true
	  In: path
	*/
	ChatroomHash string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostChatroomsChatroomHashMessagesParams() beforehand.
func (o *PostChatroomsChatroomHashMessagesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body apimodel.MessageRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	}
	rChatroomHash, rhkChatroomHash, _ := route.Params.GetOK("chatroom_hash")
	if err := o.bindChatroomHash(rChatroomHash, rhkChatroomHash, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChatroomHash binds and validates parameter ChatroomHash from path.
func (o *PostChatroomsChatroomHashMessagesParams) bindChatroomHash(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ChatroomHash = raw

	return nil
}
