// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostChatroomsChatroomHashMessagesOKCode is the HTTP code returned for type PostChatroomsChatroomHashMessagesOK
const PostChatroomsChatroomHashMessagesOKCode int = 200

/*PostChatroomsChatroomHashMessagesOK ok

swagger:response postChatroomsChatroomHashMessagesOK
*/
type PostChatroomsChatroomHashMessagesOK struct {

	/*
	  In: Body
	*/
	Payload *apimodel.MessagesResponse `json:"body,omitempty"`
}

// NewPostChatroomsChatroomHashMessagesOK creates PostChatroomsChatroomHashMessagesOK with default headers values
func NewPostChatroomsChatroomHashMessagesOK() *PostChatroomsChatroomHashMessagesOK {

	return &PostChatroomsChatroomHashMessagesOK{}
}

// WithPayload adds the payload to the post chatrooms chatroom hash messages o k response
func (o *PostChatroomsChatroomHashMessagesOK) WithPayload(payload *apimodel.MessagesResponse) *PostChatroomsChatroomHashMessagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post chatrooms chatroom hash messages o k response
func (o *PostChatroomsChatroomHashMessagesOK) SetPayload(payload *apimodel.MessagesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostChatroomsChatroomHashMessagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostChatroomsChatroomHashMessagesForbiddenCode is the HTTP code returned for type PostChatroomsChatroomHashMessagesForbidden
const PostChatroomsChatroomHashMessagesForbiddenCode int = 403

/*PostChatroomsChatroomHashMessagesForbidden error

swagger:response postChatroomsChatroomHashMessagesForbidden
*/
type PostChatroomsChatroomHashMessagesForbidden struct {

	/*
	  In: Body
	*/
	Payload *apimodel.Error `json:"body,omitempty"`
}

// NewPostChatroomsChatroomHashMessagesForbidden creates PostChatroomsChatroomHashMessagesForbidden with default headers values
func NewPostChatroomsChatroomHashMessagesForbidden() *PostChatroomsChatroomHashMessagesForbidden {

	return &PostChatroomsChatroomHashMessagesForbidden{}
}

// WithPayload adds the payload to the post chatrooms chatroom hash messages forbidden response
func (o *PostChatroomsChatroomHashMessagesForbidden) WithPayload(payload *apimodel.Error) *PostChatroomsChatroomHashMessagesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post chatrooms chatroom hash messages forbidden response
func (o *PostChatroomsChatroomHashMessagesForbidden) SetPayload(payload *apimodel.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostChatroomsChatroomHashMessagesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
