// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ChatroomFull チャットルームを完全に取得する際にでてくるやつ
// swagger:model chatroomFull
type ChatroomFull struct {

	// chatroom
	Chatroom *Chatroom `json:"chatroom,omitempty"`

	// messages
	Messages []*Message `json:"messages"`
}

// Validate validates this chatroom full
func (m *ChatroomFull) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChatroom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChatroomFull) validateChatroom(formats strfmt.Registry) error {

	if swag.IsZero(m.Chatroom) { // not required
		return nil
	}

	if m.Chatroom != nil {
		if err := m.Chatroom.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("chatroom")
			}
			return err
		}
	}

	return nil
}

func (m *ChatroomFull) validateMessages(formats strfmt.Registry) error {

	if swag.IsZero(m.Messages) { // not required
		return nil
	}

	for i := 0; i < len(m.Messages); i++ {
		if swag.IsZero(m.Messages[i]) { // not required
			continue
		}

		if m.Messages[i] != nil {
			if err := m.Messages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("messages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChatroomFull) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatroomFull) UnmarshalBinary(b []byte) error {
	var res ChatroomFull
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
