// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Chatroom チャットルームを取得するときに出てくるやつ
// swagger:model chatroom
type Chatroom struct {

	// accounts
	Accounts []*Account `json:"accounts"`

	// hash
	Hash string `json:"hash"`

	// id
	ID string `json:"id,omitempty"`

	// メッセージを全て返します。
	Messages []*Message `json:"messages"`

	// name
	Name string `json:"name"`

	// read ats
	ReadAts ReadAts `json:"readAts,omitempty"`

	// unreads count
	UnreadsCount []*UnreadCount `json:"unreadsCount"`
}

// Validate validates this chatroom
func (m *Chatroom) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccounts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReadAts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUnreadsCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Chatroom) validateAccounts(formats strfmt.Registry) error {

	if swag.IsZero(m.Accounts) { // not required
		return nil
	}

	for i := 0; i < len(m.Accounts); i++ {
		if swag.IsZero(m.Accounts[i]) { // not required
			continue
		}

		if m.Accounts[i] != nil {
			if err := m.Accounts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accounts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Chatroom) validateMessages(formats strfmt.Registry) error {

	if swag.IsZero(m.Messages) { // not required
		return nil
	}

	for i := 0; i < len(m.Messages); i++ {
		if swag.IsZero(m.Messages[i]) { // not required
			continue
		}

		if m.Messages[i] != nil {
			if err := m.Messages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("messages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Chatroom) validateReadAts(formats strfmt.Registry) error {

	if swag.IsZero(m.ReadAts) { // not required
		return nil
	}

	if err := m.ReadAts.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("readAts")
		}
		return err
	}

	return nil
}

func (m *Chatroom) validateUnreadsCount(formats strfmt.Registry) error {

	if swag.IsZero(m.UnreadsCount) { // not required
		return nil
	}

	for i := 0; i < len(m.UnreadsCount); i++ {
		if swag.IsZero(m.UnreadsCount[i]) { // not required
			continue
		}

		if m.UnreadsCount[i] != nil {
			if err := m.UnreadsCount[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("unreadsCount" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Chatroom) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Chatroom) UnmarshalBinary(b []byte) error {
	var res Chatroom
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
