// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ReadAts 最後に読んだ時間をユーザーごとに表示するオブジェクト
// swagger:model readAts
type ReadAts []*ReadAtsItems0

// Validate validates this read ats
func (m ReadAts) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ReadAtsItems0 read ats items0
// swagger:model ReadAtsItems0
type ReadAtsItems0 struct {

	// account hash
	AccountHash string `json:"accountHash,omitempty"`

	// read at
	ReadAt int64 `json:"readAt,omitempty"`
}

// Validate validates this read ats items0
func (m *ReadAtsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReadAtsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReadAtsItems0) UnmarshalBinary(b []byte) error {
	var res ReadAtsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
