// Code generated by go-swagger; DO NOT EDIT.

package apimodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// UnreadCount unread count
// swagger:model unreadCount
type UnreadCount struct {

	// account hash
	AccountHash string `json:"accountHash,omitempty"`

	// count
	Count int64 `json:"count,omitempty"`
}

// Validate validates this unread count
func (m *UnreadCount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UnreadCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnreadCount) UnmarshalBinary(b []byte) error {
	var res UnreadCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
