// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAdminSearchChatroomsParams creates a new GetAdminSearchChatroomsParams object
// no default values defined in spec.
func NewGetAdminSearchChatroomsParams() GetAdminSearchChatroomsParams {

	return GetAdminSearchChatroomsParams{}
}

// GetAdminSearchChatroomsParams contains all the bound params for the get admin search chatrooms operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAdminSearchChatrooms
type GetAdminSearchChatroomsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	AccountHash *string
	/*
	  In: query
	*/
	ChannelName *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAdminSearchChatroomsParams() beforehand.
func (o *GetAdminSearchChatroomsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAccountHash, qhkAccountHash, _ := qs.GetOK("accountHash")
	if err := o.bindAccountHash(qAccountHash, qhkAccountHash, route.Formats); err != nil {
		res = append(res, err)
	}

	qChannelName, qhkChannelName, _ := qs.GetOK("channelName")
	if err := o.bindChannelName(qChannelName, qhkChannelName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAccountHash binds and validates parameter AccountHash from query.
func (o *GetAdminSearchChatroomsParams) bindAccountHash(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.AccountHash = &raw

	return nil
}

// bindChannelName binds and validates parameter ChannelName from query.
func (o *GetAdminSearchChatroomsParams) bindChannelName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.ChannelName = &raw

	return nil
}
