// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// GetAdminSearchChatroomsOKCode is the HTTP code returned for type GetAdminSearchChatroomsOK
const GetAdminSearchChatroomsOKCode int = 200

/*GetAdminSearchChatroomsOK ok

swagger:response getAdminSearchChatroomsOK
*/
type GetAdminSearchChatroomsOK struct {

	/*
	  In: Body
	*/
	Payload *GetAdminSearchChatroomsOKBody `json:"body,omitempty"`
}

// NewGetAdminSearchChatroomsOK creates GetAdminSearchChatroomsOK with default headers values
func NewGetAdminSearchChatroomsOK() *GetAdminSearchChatroomsOK {

	return &GetAdminSearchChatroomsOK{}
}

// WithPayload adds the payload to the get admin search chatrooms o k response
func (o *GetAdminSearchChatroomsOK) WithPayload(payload *GetAdminSearchChatroomsOKBody) *GetAdminSearchChatroomsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get admin search chatrooms o k response
func (o *GetAdminSearchChatroomsOK) SetPayload(payload *GetAdminSearchChatroomsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdminSearchChatroomsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAdminSearchChatroomsForbiddenCode is the HTTP code returned for type GetAdminSearchChatroomsForbidden
const GetAdminSearchChatroomsForbiddenCode int = 403

/*GetAdminSearchChatroomsForbidden error

swagger:response getAdminSearchChatroomsForbidden
*/
type GetAdminSearchChatroomsForbidden struct {

	/*
	  In: Body
	*/
	Payload *apimodel.Error `json:"body,omitempty"`
}

// NewGetAdminSearchChatroomsForbidden creates GetAdminSearchChatroomsForbidden with default headers values
func NewGetAdminSearchChatroomsForbidden() *GetAdminSearchChatroomsForbidden {

	return &GetAdminSearchChatroomsForbidden{}
}

// WithPayload adds the payload to the get admin search chatrooms forbidden response
func (o *GetAdminSearchChatroomsForbidden) WithPayload(payload *apimodel.Error) *GetAdminSearchChatroomsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get admin search chatrooms forbidden response
func (o *GetAdminSearchChatroomsForbidden) SetPayload(payload *apimodel.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdminSearchChatroomsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
