// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// GetChatroomsIDOKCode is the HTTP code returned for type GetChatroomsIDOK
const GetChatroomsIDOKCode int = 200

/*GetChatroomsIDOK ok

swagger:response getChatroomsIdOK
*/
type GetChatroomsIDOK struct {

	/*
	  In: Body
	*/
	Payload *apimodel.Chatroom `json:"body,omitempty"`
}

// NewGetChatroomsIDOK creates GetChatroomsIDOK with default headers values
func NewGetChatroomsIDOK() *GetChatroomsIDOK {

	return &GetChatroomsIDOK{}
}

// WithPayload adds the payload to the get chatrooms Id o k response
func (o *GetChatroomsIDOK) WithPayload(payload *apimodel.Chatroom) *GetChatroomsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get chatrooms Id o k response
func (o *GetChatroomsIDOK) SetPayload(payload *apimodel.Chatroom) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChatroomsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChatroomsIDForbiddenCode is the HTTP code returned for type GetChatroomsIDForbidden
const GetChatroomsIDForbiddenCode int = 403

/*GetChatroomsIDForbidden error

swagger:response getChatroomsIdForbidden
*/
type GetChatroomsIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *apimodel.Error `json:"body,omitempty"`
}

// NewGetChatroomsIDForbidden creates GetChatroomsIDForbidden with default headers values
func NewGetChatroomsIDForbidden() *GetChatroomsIDForbidden {

	return &GetChatroomsIDForbidden{}
}

// WithPayload adds the payload to the get chatrooms Id forbidden response
func (o *GetChatroomsIDForbidden) WithPayload(payload *apimodel.Error) *GetChatroomsIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get chatrooms Id forbidden response
func (o *GetChatroomsIDForbidden) SetPayload(payload *apimodel.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChatroomsIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
