// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostChatroomsChannelHashReadOKCode is the HTTP code returned for type PostChatroomsChannelHashReadOK
const PostChatroomsChannelHashReadOKCode int = 200

/*PostChatroomsChannelHashReadOK ok

swagger:response postChatroomsChannelHashReadOK
*/
type PostChatroomsChannelHashReadOK struct {

	/*
	  In: Body
	*/
	Payload *apimodel.MessagesResponse `json:"body,omitempty"`
}

// NewPostChatroomsChannelHashReadOK creates PostChatroomsChannelHashReadOK with default headers values
func NewPostChatroomsChannelHashReadOK() *PostChatroomsChannelHashReadOK {

	return &PostChatroomsChannelHashReadOK{}
}

// WithPayload adds the payload to the post chatrooms channel hash read o k response
func (o *PostChatroomsChannelHashReadOK) WithPayload(payload *apimodel.MessagesResponse) *PostChatroomsChannelHashReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post chatrooms channel hash read o k response
func (o *PostChatroomsChannelHashReadOK) SetPayload(payload *apimodel.MessagesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostChatroomsChannelHashReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostChatroomsChannelHashReadForbiddenCode is the HTTP code returned for type PostChatroomsChannelHashReadForbidden
const PostChatroomsChannelHashReadForbiddenCode int = 403

/*PostChatroomsChannelHashReadForbidden error

swagger:response postChatroomsChannelHashReadForbidden
*/
type PostChatroomsChannelHashReadForbidden struct {

	/*
	  In: Body
	*/
	Payload *apimodel.Error `json:"body,omitempty"`
}

// NewPostChatroomsChannelHashReadForbidden creates PostChatroomsChannelHashReadForbidden with default headers values
func NewPostChatroomsChannelHashReadForbidden() *PostChatroomsChannelHashReadForbidden {

	return &PostChatroomsChannelHashReadForbidden{}
}

// WithPayload adds the payload to the post chatrooms channel hash read forbidden response
func (o *PostChatroomsChannelHashReadForbidden) WithPayload(payload *apimodel.Error) *PostChatroomsChannelHashReadForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post chatrooms channel hash read forbidden response
func (o *PostChatroomsChannelHashReadForbidden) SetPayload(payload *apimodel.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostChatroomsChannelHashReadForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
