// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostChatroomsHandlerFunc turns a function with the right signature into a post chatrooms handler
type PostChatroomsHandlerFunc func(PostChatroomsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostChatroomsHandlerFunc) Handle(params PostChatroomsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostChatroomsHandler interface for that can handle valid post chatrooms params
type PostChatroomsHandler interface {
	Handle(PostChatroomsParams, interface{}) middleware.Responder
}

// NewPostChatrooms creates a new http.Handler for the post chatrooms operation
func NewPostChatrooms(ctx *middleware.Context, handler PostChatroomsHandler) *PostChatrooms {
	return &PostChatrooms{Context: ctx, Handler: handler}
}

/*PostChatrooms swagger:route POST /chatrooms chatrooms postChatrooms

チャットルームの一覧が取ってこれるよ

一覧が出るよ.それぞれの文字列はこの形でお願いします。
{ accountHashList: ["userId", "userId"], channelName: "name" }

*/
type PostChatrooms struct {
	Context *middleware.Context
	Handler PostChatroomsHandler
}

func (o *PostChatrooms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostChatroomsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostChatroomsOKBody post chatrooms o k body
// swagger:model PostChatroomsOKBody
type PostChatroomsOKBody struct {

	// chatrooms
	Chatrooms []*apimodel.Chatroom `json:"chatrooms"`
}

// Validate validates this post chatrooms o k body
func (o *PostChatroomsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateChatrooms(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostChatroomsOKBody) validateChatrooms(formats strfmt.Registry) error {

	if swag.IsZero(o.Chatrooms) { // not required
		return nil
	}

	for i := 0; i < len(o.Chatrooms); i++ {
		if swag.IsZero(o.Chatrooms[i]) { // not required
			continue
		}

		if o.Chatrooms[i] != nil {
			if err := o.Chatrooms[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("postChatroomsOK" + "." + "chatrooms" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostChatroomsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostChatroomsOKBody) UnmarshalBinary(b []byte) error {
	var res PostChatroomsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
