// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new chatrooms API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for chatrooms API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetAdminSearchChatrooms アドミンがユーザーのhashを使ってチャットルームを取ってくるためのやつs

accountHashとchannelNameが指定されなかった場合、全部のchatroomsを返します。
*/
func (a *Client) GetAdminSearchChatrooms(params *GetAdminSearchChatroomsParams) (*GetAdminSearchChatroomsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAdminSearchChatroomsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetAdminSearchChatrooms",
		Method:             "GET",
		PathPattern:        "/admin/search/chatrooms",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAdminSearchChatroomsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAdminSearchChatroomsOK), nil

}

/*
GetChatroomsID メッセージの一覧が取ってこれるよs

一覧が頑張るよ
*/
func (a *Client) GetChatroomsID(params *GetChatroomsIDParams) (*GetChatroomsIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetChatroomsIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetChatroomsID",
		Method:             "GET",
		PathPattern:        "/chatrooms/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetChatroomsIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetChatroomsIDOK), nil

}

/*
PostChatrooms チャットルームの一覧が取ってこれるよs

一覧が出るよ.それぞれの文字列はこの形でお願いします。
{ accounts: ["userId", "userId"], channelName: "name" }
*/
func (a *Client) PostChatrooms(params *PostChatroomsParams) (*PostChatroomsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostChatroomsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostChatrooms",
		Method:             "POST",
		PathPattern:        "/chatrooms",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostChatroomsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostChatroomsOK), nil

}

/*
PostChatroomsChannelHashRead 全部既読にするやつs
*/
func (a *Client) PostChatroomsChannelHashRead(params *PostChatroomsChannelHashReadParams) (*PostChatroomsChannelHashReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostChatroomsChannelHashReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostChatroomsChannelHashRead",
		Method:             "POST",
		PathPattern:        "/chatrooms/{channel_hash}/read",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostChatroomsChannelHashReadReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostChatroomsChannelHashReadOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
