// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// GetChatroomsIDReader is a Reader for the GetChatroomsID structure.
type GetChatroomsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChatroomsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetChatroomsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetChatroomsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetChatroomsIDOK creates a GetChatroomsIDOK with default headers values
func NewGetChatroomsIDOK() *GetChatroomsIDOK {
	return &GetChatroomsIDOK{}
}

/*GetChatroomsIDOK handles this case with default header values.

ok
*/
type GetChatroomsIDOK struct {
	Payload *apimodel.Chatroom
}

func (o *GetChatroomsIDOK) Error() string {
	return fmt.Sprintf("[GET /chatrooms/{id}][%d] getChatroomsIdOK  %+v", 200, o.Payload)
}

func (o *GetChatroomsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Chatroom)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChatroomsIDForbidden creates a GetChatroomsIDForbidden with default headers values
func NewGetChatroomsIDForbidden() *GetChatroomsIDForbidden {
	return &GetChatroomsIDForbidden{}
}

/*GetChatroomsIDForbidden handles this case with default header values.

error
*/
type GetChatroomsIDForbidden struct {
	Payload *apimodel.Error
}

func (o *GetChatroomsIDForbidden) Error() string {
	return fmt.Sprintf("[GET /chatrooms/{id}][%d] getChatroomsIdForbidden  %+v", 403, o.Payload)
}

func (o *GetChatroomsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
