// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// GetAdminSearchChatroomsReader is a Reader for the GetAdminSearchChatrooms structure.
type GetAdminSearchChatroomsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAdminSearchChatroomsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAdminSearchChatroomsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetAdminSearchChatroomsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAdminSearchChatroomsOK creates a GetAdminSearchChatroomsOK with default headers values
func NewGetAdminSearchChatroomsOK() *GetAdminSearchChatroomsOK {
	return &GetAdminSearchChatroomsOK{}
}

/*GetAdminSearchChatroomsOK handles this case with default header values.

ok
*/
type GetAdminSearchChatroomsOK struct {
	Payload *GetAdminSearchChatroomsOKBody
}

func (o *GetAdminSearchChatroomsOK) Error() string {
	return fmt.Sprintf("[GET /admin/search/chatrooms][%d] getAdminSearchChatroomsOK  %+v", 200, o.Payload)
}

func (o *GetAdminSearchChatroomsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAdminSearchChatroomsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAdminSearchChatroomsForbidden creates a GetAdminSearchChatroomsForbidden with default headers values
func NewGetAdminSearchChatroomsForbidden() *GetAdminSearchChatroomsForbidden {
	return &GetAdminSearchChatroomsForbidden{}
}

/*GetAdminSearchChatroomsForbidden handles this case with default header values.

error
*/
type GetAdminSearchChatroomsForbidden struct {
	Payload *apimodel.Error
}

func (o *GetAdminSearchChatroomsForbidden) Error() string {
	return fmt.Sprintf("[GET /admin/search/chatrooms][%d] getAdminSearchChatroomsForbidden  %+v", 403, o.Payload)
}

func (o *GetAdminSearchChatroomsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetAdminSearchChatroomsOKBody get admin search chatrooms o k body
swagger:model GetAdminSearchChatroomsOKBody
*/
type GetAdminSearchChatroomsOKBody struct {

	// chatrooms
	Chatrooms []*apimodel.Chatroom `json:"chatrooms"`
}

// Validate validates this get admin search chatrooms o k body
func (o *GetAdminSearchChatroomsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateChatrooms(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAdminSearchChatroomsOKBody) validateChatrooms(formats strfmt.Registry) error {

	if swag.IsZero(o.Chatrooms) { // not required
		return nil
	}

	for i := 0; i < len(o.Chatrooms); i++ {
		if swag.IsZero(o.Chatrooms[i]) { // not required
			continue
		}

		if o.Chatrooms[i] != nil {
			if err := o.Chatrooms[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getAdminSearchChatroomsOK" + "." + "chatrooms" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAdminSearchChatroomsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAdminSearchChatroomsOKBody) UnmarshalBinary(b []byte) error {
	var res GetAdminSearchChatroomsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
