// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostChatroomsChannelHashReadParams creates a new PostChatroomsChannelHashReadParams object
// with the default values initialized.
func NewPostChatroomsChannelHashReadParams() *PostChatroomsChannelHashReadParams {
	var ()
	return &PostChatroomsChannelHashReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChatroomsChannelHashReadParamsWithTimeout creates a new PostChatroomsChannelHashReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChatroomsChannelHashReadParamsWithTimeout(timeout time.Duration) *PostChatroomsChannelHashReadParams {
	var ()
	return &PostChatroomsChannelHashReadParams{

		timeout: timeout,
	}
}

// NewPostChatroomsChannelHashReadParamsWithContext creates a new PostChatroomsChannelHashReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChatroomsChannelHashReadParamsWithContext(ctx context.Context) *PostChatroomsChannelHashReadParams {
	var ()
	return &PostChatroomsChannelHashReadParams{

		Context: ctx,
	}
}

// NewPostChatroomsChannelHashReadParamsWithHTTPClient creates a new PostChatroomsChannelHashReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChatroomsChannelHashReadParamsWithHTTPClient(client *http.Client) *PostChatroomsChannelHashReadParams {
	var ()
	return &PostChatroomsChannelHashReadParams{
		HTTPClient: client,
	}
}

/*PostChatroomsChannelHashReadParams contains all the parameters to send to the API endpoint
for the post chatrooms channel hash read operation typically these are written to a http.Request
*/
type PostChatroomsChannelHashReadParams struct {

	/*ChannelHash
	  長いハッシュ値

	*/
	ChannelHash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) WithTimeout(timeout time.Duration) *PostChatroomsChannelHashReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) WithContext(ctx context.Context) *PostChatroomsChannelHashReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) WithHTTPClient(client *http.Client) *PostChatroomsChannelHashReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChannelHash adds the channelHash to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) WithChannelHash(channelHash string) *PostChatroomsChannelHashReadParams {
	o.SetChannelHash(channelHash)
	return o
}

// SetChannelHash adds the channelHash to the post chatrooms channel hash read params
func (o *PostChatroomsChannelHashReadParams) SetChannelHash(channelHash string) {
	o.ChannelHash = channelHash
}

// WriteToRequest writes these params to a swagger request
func (o *PostChatroomsChannelHashReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param channel_hash
	if err := r.SetPathParam("channel_hash", o.ChannelHash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
