// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostChatroomsChannelHashReadReader is a Reader for the PostChatroomsChannelHashRead structure.
type PostChatroomsChannelHashReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostChatroomsChannelHashReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostChatroomsChannelHashReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewPostChatroomsChannelHashReadForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostChatroomsChannelHashReadOK creates a PostChatroomsChannelHashReadOK with default headers values
func NewPostChatroomsChannelHashReadOK() *PostChatroomsChannelHashReadOK {
	return &PostChatroomsChannelHashReadOK{}
}

/*PostChatroomsChannelHashReadOK handles this case with default header values.

ok
*/
type PostChatroomsChannelHashReadOK struct {
	Payload *apimodel.MessagesResponse
}

func (o *PostChatroomsChannelHashReadOK) Error() string {
	return fmt.Sprintf("[POST /chatrooms/{channel_hash}/read][%d] postChatroomsChannelHashReadOK  %+v", 200, o.Payload)
}

func (o *PostChatroomsChannelHashReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.MessagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostChatroomsChannelHashReadForbidden creates a PostChatroomsChannelHashReadForbidden with default headers values
func NewPostChatroomsChannelHashReadForbidden() *PostChatroomsChannelHashReadForbidden {
	return &PostChatroomsChannelHashReadForbidden{}
}

/*PostChatroomsChannelHashReadForbidden handles this case with default header values.

error
*/
type PostChatroomsChannelHashReadForbidden struct {
	Payload *apimodel.Error
}

func (o *PostChatroomsChannelHashReadForbidden) Error() string {
	return fmt.Sprintf("[POST /chatrooms/{channel_hash}/read][%d] postChatroomsChannelHashReadForbidden  %+v", 403, o.Payload)
}

func (o *PostChatroomsChannelHashReadForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
