// Code generated by go-swagger; DO NOT EDIT.

package chatrooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// NewPostChatroomsParams creates a new PostChatroomsParams object
// with the default values initialized.
func NewPostChatroomsParams() *PostChatroomsParams {
	var ()
	return &PostChatroomsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChatroomsParamsWithTimeout creates a new PostChatroomsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChatroomsParamsWithTimeout(timeout time.Duration) *PostChatroomsParams {
	var ()
	return &PostChatroomsParams{

		timeout: timeout,
	}
}

// NewPostChatroomsParamsWithContext creates a new PostChatroomsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChatroomsParamsWithContext(ctx context.Context) *PostChatroomsParams {
	var ()
	return &PostChatroomsParams{

		Context: ctx,
	}
}

// NewPostChatroomsParamsWithHTTPClient creates a new PostChatroomsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChatroomsParamsWithHTTPClient(client *http.Client) *PostChatroomsParams {
	var ()
	return &PostChatroomsParams{
		HTTPClient: client,
	}
}

/*PostChatroomsParams contains all the parameters to send to the API endpoint
for the post chatrooms operation typically these are written to a http.Request
*/
type PostChatroomsParams struct {

	/*Body*/
	Body *apimodel.ChatroomRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post chatrooms params
func (o *PostChatroomsParams) WithTimeout(timeout time.Duration) *PostChatroomsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post chatrooms params
func (o *PostChatroomsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post chatrooms params
func (o *PostChatroomsParams) WithContext(ctx context.Context) *PostChatroomsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post chatrooms params
func (o *PostChatroomsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post chatrooms params
func (o *PostChatroomsParams) WithHTTPClient(client *http.Client) *PostChatroomsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post chatrooms params
func (o *PostChatroomsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post chatrooms params
func (o *PostChatroomsParams) WithBody(body *apimodel.ChatroomRequest) *PostChatroomsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post chatrooms params
func (o *PostChatroomsParams) SetBody(body *apimodel.ChatroomRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostChatroomsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
