// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAuthOKCode is the HTTP code returned for type PostAuthOK
const PostAuthOKCode int = 200

/*PostAuthOK 認証認可用のオブジェクト、x_chat_access_tokenのヘッダに入れて使用します。

swagger:response postAuthOK
*/
type PostAuthOK struct {
}

// NewPostAuthOK creates PostAuthOK with default headers values
func NewPostAuthOK() *PostAuthOK {

	return &PostAuthOK{}
}

// WriteResponse to the client
func (o *PostAuthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostAuthForbiddenCode is the HTTP code returned for type PostAuthForbidden
const PostAuthForbiddenCode int = 403

/*PostAuthForbidden post auth forbidden

swagger:response postAuthForbidden
*/
type PostAuthForbidden struct {
}

// NewPostAuthForbidden creates PostAuthForbidden with default headers values
func NewPostAuthForbidden() *PostAuthForbidden {

	return &PostAuthForbidden{}
}

// WriteResponse to the client
func (o *PostAuthForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
