// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// GetChatroomsChatroomHashMessagesReader is a Reader for the GetChatroomsChatroomHashMessages structure.
type GetChatroomsChatroomHashMessagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChatroomsChatroomHashMessagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetChatroomsChatroomHashMessagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetChatroomsChatroomHashMessagesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetChatroomsChatroomHashMessagesOK creates a GetChatroomsChatroomHashMessagesOK with default headers values
func NewGetChatroomsChatroomHashMessagesOK() *GetChatroomsChatroomHashMessagesOK {
	return &GetChatroomsChatroomHashMessagesOK{}
}

/*GetChatroomsChatroomHashMessagesOK handles this case with default header values.

ok
*/
type GetChatroomsChatroomHashMessagesOK struct {
	Payload *apimodel.MessagesResponse
}

func (o *GetChatroomsChatroomHashMessagesOK) Error() string {
	return fmt.Sprintf("[GET /chatrooms/{chatroom_hash}/messages][%d] getChatroomsChatroomHashMessagesOK  %+v", 200, o.Payload)
}

func (o *GetChatroomsChatroomHashMessagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.MessagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChatroomsChatroomHashMessagesForbidden creates a GetChatroomsChatroomHashMessagesForbidden with default headers values
func NewGetChatroomsChatroomHashMessagesForbidden() *GetChatroomsChatroomHashMessagesForbidden {
	return &GetChatroomsChatroomHashMessagesForbidden{}
}

/*GetChatroomsChatroomHashMessagesForbidden handles this case with default header values.

error
*/
type GetChatroomsChatroomHashMessagesForbidden struct {
	Payload *apimodel.Error
}

func (o *GetChatroomsChatroomHashMessagesForbidden) Error() string {
	return fmt.Sprintf("[GET /chatrooms/{chatroom_hash}/messages][%d] getChatroomsChatroomHashMessagesForbidden  %+v", 403, o.Payload)
}

func (o *GetChatroomsChatroomHashMessagesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
