// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChatroomsChatroomHashMessagesParams creates a new GetChatroomsChatroomHashMessagesParams object
// with the default values initialized.
func NewGetChatroomsChatroomHashMessagesParams() *GetChatroomsChatroomHashMessagesParams {
	var ()
	return &GetChatroomsChatroomHashMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChatroomsChatroomHashMessagesParamsWithTimeout creates a new GetChatroomsChatroomHashMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChatroomsChatroomHashMessagesParamsWithTimeout(timeout time.Duration) *GetChatroomsChatroomHashMessagesParams {
	var ()
	return &GetChatroomsChatroomHashMessagesParams{

		timeout: timeout,
	}
}

// NewGetChatroomsChatroomHashMessagesParamsWithContext creates a new GetChatroomsChatroomHashMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChatroomsChatroomHashMessagesParamsWithContext(ctx context.Context) *GetChatroomsChatroomHashMessagesParams {
	var ()
	return &GetChatroomsChatroomHashMessagesParams{

		Context: ctx,
	}
}

// NewGetChatroomsChatroomHashMessagesParamsWithHTTPClient creates a new GetChatroomsChatroomHashMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChatroomsChatroomHashMessagesParamsWithHTTPClient(client *http.Client) *GetChatroomsChatroomHashMessagesParams {
	var ()
	return &GetChatroomsChatroomHashMessagesParams{
		HTTPClient: client,
	}
}

/*GetChatroomsChatroomHashMessagesParams contains all the parameters to send to the API endpoint
for the get chatrooms chatroom hash messages operation typically these are written to a http.Request
*/
type GetChatroomsChatroomHashMessagesParams struct {

	/*ChatroomHash
	  長いハッシュ値

	*/
	ChatroomHash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) WithTimeout(timeout time.Duration) *GetChatroomsChatroomHashMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) WithContext(ctx context.Context) *GetChatroomsChatroomHashMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) WithHTTPClient(client *http.Client) *GetChatroomsChatroomHashMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChatroomHash adds the chatroomHash to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) WithChatroomHash(chatroomHash string) *GetChatroomsChatroomHashMessagesParams {
	o.SetChatroomHash(chatroomHash)
	return o
}

// SetChatroomHash adds the chatroomHash to the get chatrooms chatroom hash messages params
func (o *GetChatroomsChatroomHashMessagesParams) SetChatroomHash(chatroomHash string) {
	o.ChatroomHash = chatroomHash
}

// WriteToRequest writes these params to a swagger request
func (o *GetChatroomsChatroomHashMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param chatroom_hash
	if err := r.SetPathParam("chatroom_hash", o.ChatroomHash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
