// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// NewPostChatroomsChatroomHashMessagesParams creates a new PostChatroomsChatroomHashMessagesParams object
// with the default values initialized.
func NewPostChatroomsChatroomHashMessagesParams() *PostChatroomsChatroomHashMessagesParams {
	var ()
	return &PostChatroomsChatroomHashMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChatroomsChatroomHashMessagesParamsWithTimeout creates a new PostChatroomsChatroomHashMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChatroomsChatroomHashMessagesParamsWithTimeout(timeout time.Duration) *PostChatroomsChatroomHashMessagesParams {
	var ()
	return &PostChatroomsChatroomHashMessagesParams{

		timeout: timeout,
	}
}

// NewPostChatroomsChatroomHashMessagesParamsWithContext creates a new PostChatroomsChatroomHashMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChatroomsChatroomHashMessagesParamsWithContext(ctx context.Context) *PostChatroomsChatroomHashMessagesParams {
	var ()
	return &PostChatroomsChatroomHashMessagesParams{

		Context: ctx,
	}
}

// NewPostChatroomsChatroomHashMessagesParamsWithHTTPClient creates a new PostChatroomsChatroomHashMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChatroomsChatroomHashMessagesParamsWithHTTPClient(client *http.Client) *PostChatroomsChatroomHashMessagesParams {
	var ()
	return &PostChatroomsChatroomHashMessagesParams{
		HTTPClient: client,
	}
}

/*PostChatroomsChatroomHashMessagesParams contains all the parameters to send to the API endpoint
for the post chatrooms chatroom hash messages operation typically these are written to a http.Request
*/
type PostChatroomsChatroomHashMessagesParams struct {

	/*Body*/
	Body *apimodel.MessageRequest
	/*ChatroomHash
	  長いハッシュ値

	*/
	ChatroomHash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) WithTimeout(timeout time.Duration) *PostChatroomsChatroomHashMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) WithContext(ctx context.Context) *PostChatroomsChatroomHashMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) WithHTTPClient(client *http.Client) *PostChatroomsChatroomHashMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) WithBody(body *apimodel.MessageRequest) *PostChatroomsChatroomHashMessagesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) SetBody(body *apimodel.MessageRequest) {
	o.Body = body
}

// WithChatroomHash adds the chatroomHash to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) WithChatroomHash(chatroomHash string) *PostChatroomsChatroomHashMessagesParams {
	o.SetChatroomHash(chatroomHash)
	return o
}

// SetChatroomHash adds the chatroomHash to the post chatrooms chatroom hash messages params
func (o *PostChatroomsChatroomHashMessagesParams) SetChatroomHash(chatroomHash string) {
	o.ChatroomHash = chatroomHash
}

// WriteToRequest writes these params to a swagger request
func (o *PostChatroomsChatroomHashMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param chatroom_hash
	if err := r.SetPathParam("chatroom_hash", o.ChatroomHash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
