// Code generated by go-swagger; DO NOT EDIT.

package messages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostChatroomsChatroomHashMessagesReader is a Reader for the PostChatroomsChatroomHashMessages structure.
type PostChatroomsChatroomHashMessagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostChatroomsChatroomHashMessagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostChatroomsChatroomHashMessagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewPostChatroomsChatroomHashMessagesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostChatroomsChatroomHashMessagesOK creates a PostChatroomsChatroomHashMessagesOK with default headers values
func NewPostChatroomsChatroomHashMessagesOK() *PostChatroomsChatroomHashMessagesOK {
	return &PostChatroomsChatroomHashMessagesOK{}
}

/*PostChatroomsChatroomHashMessagesOK handles this case with default header values.

ok
*/
type PostChatroomsChatroomHashMessagesOK struct {
	Payload *apimodel.MessagesResponse
}

func (o *PostChatroomsChatroomHashMessagesOK) Error() string {
	return fmt.Sprintf("[POST /chatrooms/{chatroom_hash}/messages][%d] postChatroomsChatroomHashMessagesOK  %+v", 200, o.Payload)
}

func (o *PostChatroomsChatroomHashMessagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.MessagesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostChatroomsChatroomHashMessagesForbidden creates a PostChatroomsChatroomHashMessagesForbidden with default headers values
func NewPostChatroomsChatroomHashMessagesForbidden() *PostChatroomsChatroomHashMessagesForbidden {
	return &PostChatroomsChatroomHashMessagesForbidden{}
}

/*PostChatroomsChatroomHashMessagesForbidden handles this case with default header values.

error
*/
type PostChatroomsChatroomHashMessagesForbidden struct {
	Payload *apimodel.Error
}

func (o *PostChatroomsChatroomHashMessagesForbidden) Error() string {
	return fmt.Sprintf("[POST /chatrooms/{chatroom_hash}/messages][%d] postChatroomsChatroomHashMessagesForbidden  %+v", 403, o.Payload)
}

func (o *PostChatroomsChatroomHashMessagesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
