// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostProfileReader is a Reader for the PostProfile structure.
type PostProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewPostProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostProfileOK creates a PostProfileOK with default headers values
func NewPostProfileOK() *PostProfileOK {
	return &PostProfileOK{}
}

/*PostProfileOK handles this case with default header values.

ok
*/
type PostProfileOK struct {
	Payload *apimodel.Account
}

func (o *PostProfileOK) Error() string {
	return fmt.Sprintf("[POST /profile][%d] postProfileOK  %+v", 200, o.Payload)
}

func (o *PostProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Account)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostProfileForbidden creates a PostProfileForbidden with default headers values
func NewPostProfileForbidden() *PostProfileForbidden {
	return &PostProfileForbidden{}
}

/*PostProfileForbidden handles this case with default header values.

error
*/
type PostProfileForbidden struct {
	Payload *apimodel.Error
}

func (o *PostProfileForbidden) Error() string {
	return fmt.Sprintf("[POST /profile][%d] postProfileForbidden  %+v", 403, o.Payload)
}

func (o *PostProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(apimodel.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostProfileBody post profile body
swagger:model PostProfileBody
*/
type PostProfileBody struct {

	// image URL
	ImageURL string `json:"imageURL,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// push token
	PushToken string `json:"pushToken,omitempty"`
}

// Validate validates this post profile body
func (o *PostProfileBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostProfileBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostProfileBody) UnmarshalBinary(b []byte) error {
	var res PostProfileBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
