// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	apimodel "github.com/kameike/chat_api/apimodel"
)

// PostChatroomsOKCode is the HTTP code returned for type PostChatroomsOK
const PostChatroomsOKCode int = 200

/*PostChatroomsOK ok

swagger:response postChatroomsOK
*/
type PostChatroomsOK struct {

	/*
	  In: Body
	*/
	Payload []*apimodel.Chatroom `json:"body,omitempty"`
}

// NewPostChatroomsOK creates PostChatroomsOK with default headers values
func NewPostChatroomsOK() *PostChatroomsOK {

	return &PostChatroomsOK{}
}

// WithPayload adds the payload to the post chatrooms o k response
func (o *PostChatroomsOK) WithPayload(payload []*apimodel.Chatroom) *PostChatroomsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post chatrooms o k response
func (o *PostChatroomsOK) SetPayload(payload []*apimodel.Chatroom) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostChatroomsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*apimodel.Chatroom, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
