// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostChatroomsIDMessagesOKCode is the HTTP code returned for type PostChatroomsIDMessagesOK
const PostChatroomsIDMessagesOKCode int = 200

/*PostChatroomsIDMessagesOK チャットルームを完全に取得する際にでてくるやつ

swagger:response postChatroomsIdMessagesOK
*/
type PostChatroomsIDMessagesOK struct {
}

// NewPostChatroomsIDMessagesOK creates PostChatroomsIDMessagesOK with default headers values
func NewPostChatroomsIDMessagesOK() *PostChatroomsIDMessagesOK {

	return &PostChatroomsIDMessagesOK{}
}

// WriteResponse to the client
func (o *PostChatroomsIDMessagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
