// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostProfileParams creates a new PostProfileParams object
// no default values defined in spec.
func NewPostProfileParams() PostProfileParams {

	return PostProfileParams{}
}

// PostProfileParams contains all the bound params for the post profile operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostProfile
type PostProfileParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*画像のURL
	  In: query
	*/
	ImageURL *string
	/*名前
	  In: query
	*/
	Name *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostProfileParams() beforehand.
func (o *PostProfileParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qImageURL, qhkImageURL, _ := qs.GetOK("imageUrl")
	if err := o.bindImageURL(qImageURL, qhkImageURL, route.Formats); err != nil {
		res = append(res, err)
	}

	qName, qhkName, _ := qs.GetOK("name")
	if err := o.bindName(qName, qhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindImageURL binds and validates parameter ImageURL from query.
func (o *PostProfileParams) bindImageURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.ImageURL = &raw

	return nil
}

// bindName binds and validates parameter Name from query.
func (o *PostProfileParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Name = &raw

	return nil
}
