// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// PostProfileHandlerFunc turns a function with the right signature into a post profile handler
type PostProfileHandlerFunc func(PostProfileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProfileHandlerFunc) Handle(params PostProfileParams) middleware.Responder {
	return fn(params)
}

// PostProfileHandler interface for that can handle valid post profile params
type PostProfileHandler interface {
	Handle(PostProfileParams) middleware.Responder
}

// NewPostProfile creates a new http.Handler for the post profile operation
func NewPostProfile(ctx *middleware.Context, handler PostProfileHandler) *PostProfile {
	return &PostProfile{Context: ctx, Handler: handler}
}

/*PostProfile swagger:route POST /profile account postProfile

ユーザープロファイルのアップデート

nameをアップデートできます。

*/
type PostProfile struct {
	Context *middleware.Context
	Handler PostProfileHandler
}

func (o *PostProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostProfileParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostProfileBody post profile body
// swagger:model PostProfileBody
type PostProfileBody struct {

	// image URL
	ImageURL string `json:"imageURL,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// push token
	PushToken string `json:"pushToken,omitempty"`
}

// Validate validates this post profile body
func (o *PostProfileBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostProfileBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostProfileBody) UnmarshalBinary(b []byte) error {
	var res PostProfileBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
