// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostProfileHandlerFunc turns a function with the right signature into a post profile handler
type PostProfileHandlerFunc func(PostProfileParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProfileHandlerFunc) Handle(params PostProfileParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostProfileHandler interface for that can handle valid post profile params
type PostProfileHandler interface {
	Handle(PostProfileParams, interface{}) middleware.Responder
}

// NewPostProfile creates a new http.Handler for the post profile operation
func NewPostProfile(ctx *middleware.Context, handler PostProfileHandler) *PostProfile {
	return &PostProfile{Context: ctx, Handler: handler}
}

/*PostProfile swagger:route POST /profile account postProfile

ユーザープロファイルのアップデート

nameをアップデートできます。

*/
type PostProfile struct {
	Context *middleware.Context
	Handler PostProfileHandler
}

func (o *PostProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostProfileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
