// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChatroomsIDParams creates a new GetChatroomsIDParams object
// with the default values initialized.
func NewGetChatroomsIDParams() *GetChatroomsIDParams {
	var ()
	return &GetChatroomsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChatroomsIDParamsWithTimeout creates a new GetChatroomsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChatroomsIDParamsWithTimeout(timeout time.Duration) *GetChatroomsIDParams {
	var ()
	return &GetChatroomsIDParams{

		timeout: timeout,
	}
}

// NewGetChatroomsIDParamsWithContext creates a new GetChatroomsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChatroomsIDParamsWithContext(ctx context.Context) *GetChatroomsIDParams {
	var ()
	return &GetChatroomsIDParams{

		Context: ctx,
	}
}

// NewGetChatroomsIDParamsWithHTTPClient creates a new GetChatroomsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChatroomsIDParamsWithHTTPClient(client *http.Client) *GetChatroomsIDParams {
	var ()
	return &GetChatroomsIDParams{
		HTTPClient: client,
	}
}

/*GetChatroomsIDParams contains all the parameters to send to the API endpoint
for the get chatrooms ID operation typically these are written to a http.Request
*/
type GetChatroomsIDParams struct {

	/*ID
	  長いハッシュ値

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get chatrooms ID params
func (o *GetChatroomsIDParams) WithTimeout(timeout time.Duration) *GetChatroomsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get chatrooms ID params
func (o *GetChatroomsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get chatrooms ID params
func (o *GetChatroomsIDParams) WithContext(ctx context.Context) *GetChatroomsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get chatrooms ID params
func (o *GetChatroomsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get chatrooms ID params
func (o *GetChatroomsIDParams) WithHTTPClient(client *http.Client) *GetChatroomsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get chatrooms ID params
func (o *GetChatroomsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get chatrooms ID params
func (o *GetChatroomsIDParams) WithID(id string) *GetChatroomsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get chatrooms ID params
func (o *GetChatroomsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetChatroomsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
