// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// NewPostChatroomsIDMessagesParams creates a new PostChatroomsIDMessagesParams object
// with the default values initialized.
func NewPostChatroomsIDMessagesParams() *PostChatroomsIDMessagesParams {
	var ()
	return &PostChatroomsIDMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChatroomsIDMessagesParamsWithTimeout creates a new PostChatroomsIDMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChatroomsIDMessagesParamsWithTimeout(timeout time.Duration) *PostChatroomsIDMessagesParams {
	var ()
	return &PostChatroomsIDMessagesParams{

		timeout: timeout,
	}
}

// NewPostChatroomsIDMessagesParamsWithContext creates a new PostChatroomsIDMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChatroomsIDMessagesParamsWithContext(ctx context.Context) *PostChatroomsIDMessagesParams {
	var ()
	return &PostChatroomsIDMessagesParams{

		Context: ctx,
	}
}

// NewPostChatroomsIDMessagesParamsWithHTTPClient creates a new PostChatroomsIDMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChatroomsIDMessagesParamsWithHTTPClient(client *http.Client) *PostChatroomsIDMessagesParams {
	var ()
	return &PostChatroomsIDMessagesParams{
		HTTPClient: client,
	}
}

/*PostChatroomsIDMessagesParams contains all the parameters to send to the API endpoint
for the post chatrooms ID messages operation typically these are written to a http.Request
*/
type PostChatroomsIDMessagesParams struct {

	/*Body*/
	Body *apimodel.ChatCreate
	/*ID
	  長いハッシュ値

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) WithTimeout(timeout time.Duration) *PostChatroomsIDMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) WithContext(ctx context.Context) *PostChatroomsIDMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) WithHTTPClient(client *http.Client) *PostChatroomsIDMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) WithBody(body *apimodel.ChatCreate) *PostChatroomsIDMessagesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) SetBody(body *apimodel.ChatCreate) {
	o.Body = body
}

// WithID adds the id to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) WithID(id string) *PostChatroomsIDMessagesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post chatrooms ID messages params
func (o *PostChatroomsIDMessagesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostChatroomsIDMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
