// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostChatroomsIDReadParams creates a new PostChatroomsIDReadParams object
// with the default values initialized.
func NewPostChatroomsIDReadParams() *PostChatroomsIDReadParams {
	var ()
	return &PostChatroomsIDReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostChatroomsIDReadParamsWithTimeout creates a new PostChatroomsIDReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostChatroomsIDReadParamsWithTimeout(timeout time.Duration) *PostChatroomsIDReadParams {
	var ()
	return &PostChatroomsIDReadParams{

		timeout: timeout,
	}
}

// NewPostChatroomsIDReadParamsWithContext creates a new PostChatroomsIDReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostChatroomsIDReadParamsWithContext(ctx context.Context) *PostChatroomsIDReadParams {
	var ()
	return &PostChatroomsIDReadParams{

		Context: ctx,
	}
}

// NewPostChatroomsIDReadParamsWithHTTPClient creates a new PostChatroomsIDReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostChatroomsIDReadParamsWithHTTPClient(client *http.Client) *PostChatroomsIDReadParams {
	var ()
	return &PostChatroomsIDReadParams{
		HTTPClient: client,
	}
}

/*PostChatroomsIDReadParams contains all the parameters to send to the API endpoint
for the post chatrooms ID read operation typically these are written to a http.Request
*/
type PostChatroomsIDReadParams struct {

	/*ID
	  長いハッシュ値

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) WithTimeout(timeout time.Duration) *PostChatroomsIDReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) WithContext(ctx context.Context) *PostChatroomsIDReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) WithHTTPClient(client *http.Client) *PostChatroomsIDReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) WithID(id string) *PostChatroomsIDReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post chatrooms ID read params
func (o *PostChatroomsIDReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostChatroomsIDReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
