// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostChatroomsIDReadReader is a Reader for the PostChatroomsIDRead structure.
type PostChatroomsIDReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostChatroomsIDReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostChatroomsIDReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostChatroomsIDReadOK creates a PostChatroomsIDReadOK with default headers values
func NewPostChatroomsIDReadOK() *PostChatroomsIDReadOK {
	return &PostChatroomsIDReadOK{}
}

/*PostChatroomsIDReadOK handles this case with default header values.

更新されたメッセージ一覧
*/
type PostChatroomsIDReadOK struct {
	Payload []*apimodel.Message
}

func (o *PostChatroomsIDReadOK) Error() string {
	return fmt.Sprintf("[POST /chatrooms/{id}/read][%d] postChatroomsIdReadOK  %+v", 200, o.Payload)
}

func (o *PostChatroomsIDReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
