// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "From the todo list tutorial on goswagger.io",
    "title": "Taimme-Chat",
    "version": "1.0.0"
  },
  "paths": {
    "/admin/search/chatrooms": {
      "get": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "accountHashとchannelNameが指定されなかった場合、全部のchatroomsを返します。",
        "tags": [
          "chatrooms"
        ],
        "summary": "アドミンがユーザーのhashを使ってチャットルームを取ってくるためのやつ",
        "parameters": [
          {
            "type": "string",
            "name": "accountHash",
            "in": "query"
          },
          {
            "type": "string",
            "name": "channelName",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "chatrooms": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/chatroom"
                  }
                }
              }
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/auth": {
      "post": {
        "description": "サインアップもしくはアクセストークンの更新を行います",
        "tags": [
          "account"
        ],
        "summary": "ログイン",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "accountHash": {
                  "type": "string"
                },
                "authToken": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/authInfo"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/chatrooms": {
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "一覧が出るよ.それぞれの文字列はこの形でお願いします。\n{ accounts: [\"userId\", \"userId\"], channelName: \"name\" } ",
        "tags": [
          "chatrooms"
        ],
        "summary": "チャットルームの一覧が取ってこれるよ",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/chatroomRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "chatrooms": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/chatroom"
                  }
                }
              }
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/chatrooms/{channel_hash}/read": {
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "tags": [
          "chatrooms"
        ],
        "summary": "全部既読にするやつ",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/messagesResponse"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "長いハッシュ値",
          "name": "channel_hash",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chatrooms/{chatroom_hash}/messages": {
      "get": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "tags": [
          "messages"
        ],
        "summary": "メッセージの取得",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/messagesResponse"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "tags": [
          "messages"
        ],
        "summary": "メッセージの投稿",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/messageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/messagesResponse"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "長いハッシュ値",
          "name": "chatroom_hash",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chatrooms/{id}": {
      "get": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "一覧が頑張るよ",
        "tags": [
          "chatrooms"
        ],
        "summary": "メッセージの一覧が取ってこれるよ",
        "parameters": [
          {
            "type": "string",
            "description": "長いハッシュ値",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/chatroom"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "tags": [
          "deploy"
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "string"
            }
          },
          "503": {
            "description": "notready",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/profile": {
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "nameをアップデートできます。",
        "tags": [
          "account"
        ],
        "summary": "ユーザープロファイルのアップデート",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "imageURL": {
                  "type": "string",
                  "example": "https://hogehoge.com"
                },
                "name": {
                  "type": "string",
                  "example": "raz"
                },
                "pushToken": {
                  "type": "string",
                  "example": "GRTo4JUvDwEzJogb"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/account"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "account": {
      "description": "汎用的に出てくるユーザーオブジェクト",
      "type": "object",
      "properties": {
        "hash": {
          "type": "string",
          "example": "HAB4cQxKTQkEj7rMdE6QQW391ffpVbQshya+R66OIhfu5drm"
        },
        "id": {
          "type": "integer"
        },
        "imageURL": {
          "type": "string",
          "example": "https://hogehoge.s3.amazon.com"
        },
        "name": {
          "type": "string",
          "example": "kameike"
        }
      }
    },
    "authInfo": {
      "description": "認証認可用のオブジェクト、x_chat_access_tokenのヘッダに入れて使用します。",
      "type": "object",
      "properties": {
        "accessToken": {
          "type": "string",
          "example": "HAB4cQxKTQkEj7rMdE6QQW391ffpVbQshya+R66OIhfu5drm"
        },
        "account": {
          "$ref": "#/definitions/account"
        }
      }
    },
    "chatroom": {
      "description": "チャットルームを取得するときに出てくるやつ",
      "type": "object",
      "properties": {
        "accounts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/account"
          }
        },
        "hash": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "messages": {
          "description": "メッセージを全て返します。",
          "type": "array",
          "items": {
            "$ref": "#/definitions/message"
          }
        },
        "name": {
          "type": "string"
        },
        "readAts": {
          "$ref": "#/definitions/readAts"
        },
        "unreadsCount": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/unreadCount"
          }
        }
      }
    },
    "chatroomRequest": {
      "type": "object",
      "properties": {
        "chatrooms": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "errorMessage": {
          "description": "エラーメッセージ、中身をユーザーに見せて差し支えないものです。",
          "type": "string",
          "example": "権限がありません(code: 3)"
        }
      }
    },
    "message": {
      "type": "object",
      "properties": {
        "account": {
          "$ref": "#/definitions/account"
        },
        "content": {
          "type": "string",
          "example": "よろしくお願いします"
        },
        "createdAt": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer"
        }
      }
    },
    "messageRequest": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "example": "よろしくお願いします"
        }
      }
    },
    "messagesResponse": {
      "description": "メッセージ一覧のオブジェクト。既読情報も返す。",
      "type": "object",
      "properties": {
        "messages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/message"
          }
        },
        "readAts": {
          "$ref": "#/definitions/readAts"
        }
      }
    },
    "readAts": {
      "description": "最後に読んだ時間をユーザーごとに表示するオブジェクト",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "accountHash": {
            "type": "string"
          },
          "readAt": {
            "type": "integer",
            "format": "int64"
          }
        }
      }
    },
    "unreadCount": {
      "type": "object",
      "properties": {
        "accountHash": {
          "type": "string"
        },
        "count": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "apiKey": {
      "description": "/authエンドポイントによって送られるアクセストークン",
      "type": "apiKey",
      "name": "X-CHAT-ACCESS-TOKEN",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "From the todo list tutorial on goswagger.io",
    "title": "Taimme-Chat",
    "version": "1.0.0"
  },
  "paths": {
    "/admin/search/chatrooms": {
      "get": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "accountHashとchannelNameが指定されなかった場合、全部のchatroomsを返します。",
        "tags": [
          "chatrooms"
        ],
        "summary": "アドミンがユーザーのhashを使ってチャットルームを取ってくるためのやつ",
        "parameters": [
          {
            "type": "string",
            "name": "accountHash",
            "in": "query"
          },
          {
            "type": "string",
            "name": "channelName",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "chatrooms": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/chatroom"
                  }
                }
              }
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/auth": {
      "post": {
        "description": "サインアップもしくはアクセストークンの更新を行います",
        "tags": [
          "account"
        ],
        "summary": "ログイン",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "accountHash": {
                  "type": "string"
                },
                "authToken": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/authInfo"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/chatrooms": {
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "一覧が出るよ.それぞれの文字列はこの形でお願いします。\n{ accounts: [\"userId\", \"userId\"], channelName: \"name\" } ",
        "tags": [
          "chatrooms"
        ],
        "summary": "チャットルームの一覧が取ってこれるよ",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/chatroomRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "chatrooms": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/chatroom"
                  }
                }
              }
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/chatrooms/{channel_hash}/read": {
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "tags": [
          "chatrooms"
        ],
        "summary": "全部既読にするやつ",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/messagesResponse"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "長いハッシュ値",
          "name": "channel_hash",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chatrooms/{chatroom_hash}/messages": {
      "get": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "tags": [
          "messages"
        ],
        "summary": "メッセージの取得",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/messagesResponse"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "tags": [
          "messages"
        ],
        "summary": "メッセージの投稿",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/messageRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/messagesResponse"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "description": "長いハッシュ値",
          "name": "chatroom_hash",
          "in": "path",
          "required": true
        }
      ]
    },
    "/chatrooms/{id}": {
      "get": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "一覧が頑張るよ",
        "tags": [
          "chatrooms"
        ],
        "summary": "メッセージの一覧が取ってこれるよ",
        "parameters": [
          {
            "type": "string",
            "description": "長いハッシュ値",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/chatroom"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "tags": [
          "deploy"
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "string"
            }
          },
          "503": {
            "description": "notready",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/profile": {
      "post": {
        "security": [
          {
            "apiKey": []
          }
        ],
        "description": "nameをアップデートできます。",
        "tags": [
          "account"
        ],
        "summary": "ユーザープロファイルのアップデート",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "imageURL": {
                  "type": "string",
                  "example": "https://hogehoge.com"
                },
                "name": {
                  "type": "string",
                  "example": "raz"
                },
                "pushToken": {
                  "type": "string",
                  "example": "GRTo4JUvDwEzJogb"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "$ref": "#/definitions/account"
            }
          },
          "403": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "account": {
      "description": "汎用的に出てくるユーザーオブジェクト",
      "type": "object",
      "properties": {
        "hash": {
          "type": "string",
          "example": "HAB4cQxKTQkEj7rMdE6QQW391ffpVbQshya+R66OIhfu5drm"
        },
        "id": {
          "type": "integer"
        },
        "imageURL": {
          "type": "string",
          "example": "https://hogehoge.s3.amazon.com"
        },
        "name": {
          "type": "string",
          "example": "kameike"
        }
      }
    },
    "authInfo": {
      "description": "認証認可用のオブジェクト、x_chat_access_tokenのヘッダに入れて使用します。",
      "type": "object",
      "properties": {
        "accessToken": {
          "type": "string",
          "example": "HAB4cQxKTQkEj7rMdE6QQW391ffpVbQshya+R66OIhfu5drm"
        },
        "account": {
          "$ref": "#/definitions/account"
        }
      }
    },
    "chatroom": {
      "description": "チャットルームを取得するときに出てくるやつ",
      "type": "object",
      "properties": {
        "accounts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/account"
          }
        },
        "hash": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "messages": {
          "description": "メッセージを全て返します。",
          "type": "array",
          "items": {
            "$ref": "#/definitions/message"
          }
        },
        "name": {
          "type": "string"
        },
        "readAts": {
          "$ref": "#/definitions/readAts"
        },
        "unreadsCount": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/unreadCount"
          }
        }
      }
    },
    "chatroomRequest": {
      "type": "object",
      "properties": {
        "chatrooms": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "errorMessage": {
          "description": "エラーメッセージ、中身をユーザーに見せて差し支えないものです。",
          "type": "string",
          "example": "権限がありません(code: 3)"
        }
      }
    },
    "message": {
      "type": "object",
      "properties": {
        "account": {
          "$ref": "#/definitions/account"
        },
        "content": {
          "type": "string",
          "example": "よろしくお願いします"
        },
        "createdAt": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer"
        }
      }
    },
    "messageRequest": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "example": "よろしくお願いします"
        }
      }
    },
    "messagesResponse": {
      "description": "メッセージ一覧のオブジェクト。既読情報も返す。",
      "type": "object",
      "properties": {
        "messages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/message"
          }
        },
        "readAts": {
          "$ref": "#/definitions/readAts"
        }
      }
    },
    "readAts": {
      "description": "最後に読んだ時間をユーザーごとに表示するオブジェクト",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "accountHash": {
            "type": "string"
          },
          "readAt": {
            "type": "integer",
            "format": "int64"
          }
        }
      }
    },
    "unreadCount": {
      "type": "object",
      "properties": {
        "accountHash": {
          "type": "string"
        },
        "count": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "apiKey": {
      "description": "/authエンドポイントによって送られるアクセストークン",
      "type": "apiKey",
      "name": "X-CHAT-ACCESS-TOKEN",
      "in": "header"
    }
  }
}`))
}
