// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetChatroomsIDMessagesHandlerFunc turns a function with the right signature into a get chatrooms ID messages handler
type GetChatroomsIDMessagesHandlerFunc func(GetChatroomsIDMessagesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChatroomsIDMessagesHandlerFunc) Handle(params GetChatroomsIDMessagesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetChatroomsIDMessagesHandler interface for that can handle valid get chatrooms ID messages params
type GetChatroomsIDMessagesHandler interface {
	Handle(GetChatroomsIDMessagesParams, interface{}) middleware.Responder
}

// NewGetChatroomsIDMessages creates a new http.Handler for the get chatrooms ID messages operation
func NewGetChatroomsIDMessages(ctx *middleware.Context, handler GetChatroomsIDMessagesHandler) *GetChatroomsIDMessages {
	return &GetChatroomsIDMessages{Context: ctx, Handler: handler}
}

/*GetChatroomsIDMessages swagger:route GET /chatrooms/{id}/messages chatRooms getChatroomsIdMessages

メッセージの取得

ok

*/
type GetChatroomsIDMessages struct {
	Context *middleware.Context
	Handler GetChatroomsIDMessagesHandler
}

func (o *GetChatroomsIDMessages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChatroomsIDMessagesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
