// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	apimodel "github.com/kameike/chat_api/swggen/apimodel"
)

// PostChatroomsIDReadOKCode is the HTTP code returned for type PostChatroomsIDReadOK
const PostChatroomsIDReadOKCode int = 200

/*PostChatroomsIDReadOK 更新されたメッセージ一覧

swagger:response postChatroomsIdReadOK
*/
type PostChatroomsIDReadOK struct {

	/*
	  In: Body
	*/
	Payload []*apimodel.Message `json:"body,omitempty"`
}

// NewPostChatroomsIDReadOK creates PostChatroomsIDReadOK with default headers values
func NewPostChatroomsIDReadOK() *PostChatroomsIDReadOK {

	return &PostChatroomsIDReadOK{}
}

// WithPayload adds the payload to the post chatrooms Id read o k response
func (o *PostChatroomsIDReadOK) WithPayload(payload []*apimodel.Message) *PostChatroomsIDReadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post chatrooms Id read o k response
func (o *PostChatroomsIDReadOK) SetPayload(payload []*apimodel.Message) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostChatroomsIDReadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*apimodel.Message, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
