// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostChatroomsIDReadHandlerFunc turns a function with the right signature into a post chatrooms ID read handler
type PostChatroomsIDReadHandlerFunc func(PostChatroomsIDReadParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostChatroomsIDReadHandlerFunc) Handle(params PostChatroomsIDReadParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostChatroomsIDReadHandler interface for that can handle valid post chatrooms ID read params
type PostChatroomsIDReadHandler interface {
	Handle(PostChatroomsIDReadParams, interface{}) middleware.Responder
}

// NewPostChatroomsIDRead creates a new http.Handler for the post chatrooms ID read operation
func NewPostChatroomsIDRead(ctx *middleware.Context, handler PostChatroomsIDReadHandler) *PostChatroomsIDRead {
	return &PostChatroomsIDRead{Context: ctx, Handler: handler}
}

/*PostChatroomsIDRead swagger:route POST /chatrooms/{id}/read chatRooms postChatroomsIdRead

PostChatroomsIDRead post chatrooms ID read API

*/
type PostChatroomsIDRead struct {
	Context *middleware.Context
	Handler PostChatroomsIDReadHandler
}

func (o *PostChatroomsIDRead) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostChatroomsIDReadParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
