// Code generated by go-swagger; DO NOT EDIT.

package chat_rooms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostChatroomsHandlerFunc turns a function with the right signature into a post chatrooms handler
type PostChatroomsHandlerFunc func(PostChatroomsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostChatroomsHandlerFunc) Handle(params PostChatroomsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostChatroomsHandler interface for that can handle valid post chatrooms params
type PostChatroomsHandler interface {
	Handle(PostChatroomsParams, interface{}) middleware.Responder
}

// NewPostChatrooms creates a new http.Handler for the post chatrooms operation
func NewPostChatrooms(ctx *middleware.Context, handler PostChatroomsHandler) *PostChatrooms {
	return &PostChatrooms{Context: ctx, Handler: handler}
}

/*PostChatrooms swagger:route POST /chatrooms chatRooms postChatrooms

チャットルームの一覧が取ってこれるよ

一覧が出るよ

*/
type PostChatrooms struct {
	Context *middleware.Context
	Handler PostChatroomsHandler
}

func (o *PostChatrooms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostChatroomsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
